version: '3'

networks:
    wildadventures_network:

services:
    # microservices edge
    edgeconfig:
        build: ../application/ms-edge/ms-config
        environment:
            GIT_CONFIG_URI: ${GIT_CONFIG_URI}
            GIT_CONFIG_BRANCH: ${GIT_CONFIG_BRANCH}
        networks:
            - wildadventures_network
        command: ['java', '-jar', 'app.jar']

    edgeregistry:
      build: ../application/ms-edge/ms-registry
      environment:
        EDGE_CONFIG_HOST: edgeconfig
      depends_on:
        - edgeconfig
      networks:
        - wildadventures_network
      command: ['./wait-for-it.sh', 'edgeconfig:80', '--timeout=0', '--', 'java', '-jar', 'app.jar']

    edgegateway:
      build: ../application/ms-edge/ms-gateway
      environment:
        EDGE_CONFIG_HOST: edgeconfig
      depends_on:
        - edgeconfig
        - edgeregistry
      networks:
        - wildadventures_network
      command:
        [
          './wait-for-it.sh',
          'edgeconfig:80',
          '--timeout=0',
          '--',
          './wait-for-it.sh',
          'edgeregistry:80',
          '--timeout=0',
          '--',
          './wait-for-it.sh',
          'keycloak:8080',
          '--timeout=0',
          '--',
          'java',
          '-jar',
          'app.jar',
        ]
      ports:
        - 8080:80

    # IAM (Identity Access Management)

    keycloak:
      image: jboss/keycloak:9.0.3
      environment:
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        KEYCLOAK_IMPORT: /tmp/wild-adventures-realm.json
      networks:
        - wildadventures_network
      command:
        - '-b 0.0.0.0'
        - '-Dkeycloak.profile.feature.upload_scripts=enabled'
        - '-Dkeycloak.migration.action=import'
        - '-Dkeycloak.migration.provider=singleFile'
        - '-Dkeycloak.migration.file=/tmp/wild-adventures-realm.json'
        - '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING'
      volumes:
        - ./keycloak/wild-adventures-realm.json:/tmp/wild-adventures-realm.json
      ports:
        - 8081:8080

    # Request tracking

    zipkin:
      image: openjdk:14-jdk-alpine
      networks:
        - wildadventures_network
      command: ['java', '-jar', 'zipkin-server.jar']
      volumes:
        - ./zipkin/zipkin-server.jar:/zipkin-server.jar
      ports:
        - 9411:9411

    # microservices business

    # adventures

    adventuresmysql:
      image: mysql:8.0.19
      environment:
        MYSQL_ROOT_PASSWORD: ${ADVENTURES_MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${ADVENTURES_MYSQL_DATABASE}
        MYSQL_USER: ${ADVENTURES_MYSQL_USER}
        MYSQL_PASSWORD: ${ADVENTURES_MYSQL_PASSWORD}
      networks:
        - wildadventures_network
      volumes:
        - ./adventures-db/init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
        - ./adventures-db/adventures.cnf:/etc/mysql/conf.d/custom.cnf

    adventures:
      build: ../application/ms-business/ms-adventures
      depends_on:
        - edgeconfig
        - edgeregistry
        - adventuresmysql
      environment:
        CONFIG_HOST: edgeconfig
      networks:
        - wildadventures_network
      command:
        [
          './wait-for-it.sh',
          'edgeconfig:80',
          '--timeout=0',
          '--',
          './wait-for-it.sh',
          'edgeregistry:80',
          '--timeout=0',
          '--',
          './wait-for-it.sh',
          'adventuresmysql:3306',
          '--timeout=0',
          '--',
          'java',
          '-jar',
          'app.jar',
        ]

