version: '3'

networks:
    wildadventures_network:

services:
    # microservices edge
    edgeconfig:
        build: ../application/ms-edge/ms-config
        environment:
            GIT_CONFIG_URI: ${GIT_CONFIG_URI}
            GIT_CONFIG_BRANCH: ${GIT_CONFIG_BRANCH}
        networks:
            - wildadventures_network
        command: ['java', '-jar', 'app.jar']

    edgeregistry:
      build: ../application/ms-edge/ms-registry
      environment:
        EDGE_CONFIG_HOST: edgeconfig
      depends_on:
        - edgeconfig
      networks:
        - wildadventures_network
      command: ['./wait-for-it.sh', 'edgeconfig:80', '--timeout=0', '--', 'java', '-jar', 'app.jar']